version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - keycloak

  keycloak:
    image: jboss/keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=rsm-admin
      - KEYCLOAK_PASSWORD=rsm-admin
